# Generated by Django 5.2.14 on 2026-05-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emp_app', '0002_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('phone', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('emp_type', models.CharField(max_length=50)),
                ('salary', models.FloatField(max_length=55)),
            ],
        ),
    ]
