# Generated by Django 5.2.14 on 2026-05-25 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=200)),
                ('book_des', models.TextField(max_length=200)),
                ('book_type', models.CharField(max_length=200)),
                ('book_author', models.CharField(max_length=200)),
                ('book_price', models.CharField(max_length=200)),
                ('book_quantity', models.IntegerField()),
            ],
        ),
    ]
